FROM caddy:2-alpine

# Should run update before
# Wrong package manager
RUN apt-get install ca-certificates openssl wget

ADD files.tar .
RUN mv files/images/* .
RUN rm -rf files
RUN echo "${BUILD_INFO}" > build.info

# Run Caddy server
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
