FROM caddy:2-alpine

RUN apt-get install ca-certificates openssl wget

# Working directory is missing
WORKDIR /usr/share/caddy/

ADD files.tar .
RUN mv files/images/* .
RUN rm -rf files
RUN echo "${BUILD_INFO}" > build.info

# Run Caddy server
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
