kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  startup-args.conf: |
    {{- include "startupArgs" . | nindent 4 }}

  startup1.conf: {{ include "startupConf" . | indent 4 }}
  startup2.conf: |
    {{ include "startupConf" . | nindent 4 }}
  startup3.conf: |
    {{- include "startupConf" . | nindent 4 }}
  startup4.conf: |-
    {{ include "startupConf" . | nindent 4 }}
