kind: Secret
# What is Opaque type
# What other types can we have: ServiceAccount, ImagePullSecret, etc.
type: Opaque
apiVersion: v1
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: {{ .Release.Service | quote }}
stringData:
  db-password: {{ required "You did not provide a password for the Database" .Values.dbPassword | quote }}
